version: "3"
services:
  c1:
    image: erlang:25.0.3
    command: erl -noshell -name app@l1.com -setcookie cookie  -preventing_overlapping_partition false -pa ebin -eval "compile:file(\"/persistentserver\"), persistentserver:init_db()"
    container_name: l1.com
    volumes:
      - "./persistentserver.erl:/persistentserver.erl:rw"
    networks:
      - net1

  c2:
    image: erlang:25.0.3
    command: erl -noshell -name storage@l2.com -setcookie cookie -preventing_overlapping_partition false -pa ebin -eval "compile:file(\"/persistentserver\"), persistentserver:init_st()"
    container_name: l2.com
    volumes:
      - "./persistentserver.erl:/persistentserver.erl:rw"
    networks:
      - net1

  c3:
    image: erlang:25.0.3
    command: erl -noshell -name app@l3.com -setcookie cookie -preventing_overlapping_partition false
    container_name: l3.com
    networks:
      - net1

# We're using custom network setup, as it ships with a DNS
# system which allows containers to communicate by hostnames.
networks:
  net1:
    driver: bridge
