version: "3"
services:
  c1:
    image: erlang:25.0.3
    command: erl -noshell -name app@l1.com -setcookie cookie
    container_name: l1.com
    networks:
      - a
      - b
  c2:
    image: erlang:25.0.3
    command: erl -noshell -name app@l2.com -setcookie cookie
    container_name: l2.com
    networks:
     - a
     - c
  c3:
    image: erlang:25.0.3
    command: erl -noshell -name app@l3.com -setcookie cookie
    container_name: l3.com
    networks:
     - b
     - c
     - d
  c4:
    image: erlang:25.0.3
    command: erl -noshell -name app@l4.com -setcookie cookie
    container_name: l4.com
    networks:
      - d

  c5:
    image: erlang:25.0.3
    command: erl -noshell -name app@l5.com -setcookie cookie
    container_name: l5.com
    networks:
     - d


# We're using custom network setup, as it ships with a DNS
# system which allows containers to communicate by hostnames.
networks:
  a:
    driver: bridge
  b:
    driver: bridge
  c:
    driver: bridge
  d:
    driver: bridge
