version: "3"
services:
  c1:
    image: erlang:25.0.3
    command: erl -noshell -name app@l1.com -setcookie cookie -net_ticktime 2000 -preventing_overlapping_partition false
    container_name: l1.com
    networks:
      - net1

  c2:
    image: erlang:25.0.3
    command: erl -noshell -name app@l2.com -setcookie cookie -net_ticktime 2000 -preventing_overlapping_partition false
    container_name: l2.com
    networks:
     - net1
  c3:
    image: erlang:25.0.3
    command: erl -noshell -name app@l3.com -setcookie cookie -net_ticktime 2000 -preventing_overlapping_partition false
    container_name: l3.com
    networks:
     - net1

# We're using custom network setup, as it ships with a DNS
# system which allows containers to communicate by hostnames.
networks:
  net1:
    driver: bridge
